In [2]:
from sklearn import svm #method untuk pross perhitungan klasifikasi
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer #method untuk menghitung vsm dan tfidf
from sklearn import metrics #method untuk pembentukan matriks 1x1, 2x2, 3x3, ...
from sklearn.metrics import accuracy_score #method perhitungan akurasi
from sklearn.model_selection import KFold #Method perhitungan K-Fold
import numpy as np #scientific computing untuk array N-dimenesi
import re #re = regular expression
import itertools
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

#Razi Aziz Syahputro#
#Universitas Negeri Jakarta
#Pendidikan Teknik Informatika & Komputer#


#CASE FOLDING + LOAD FILE DOKUMEN#
dataSet = []#inisialisasi dataSet untuk menyimpan dokumen teks yang telah di looping
for i in range(1, 267):#file dokumen yg akan di looping
    f = open("dataset/%d.txt" %i, "r+")#proses membuka file
    string = f.read()#proses pembacaan file
    string = re.sub("[^a-zA-Z]", " ", string)#proses membuang karakter selain huruf diganti spasi/sub=substitusi(mereplace semua pola RE)
    string = string.lower()#proses menjadikan kalimat huruf kecil
    dataSet.append(string)#proses memasukan/mengupdate kalimat2 kedalam dataSet
    #f.close()#proses menutup file
print("Case Folding: \n", dataSet)

#LOAD FILE STOPWORDS#
stopword = []#inisialisasi dataSet untuk menyimpan dokumen teks
s = open("id.stopwords.txt", "r+")#proses membuka file
stop = s.read()#proses pembacaan file
stop = re.sub("[^a-zA-Z]", " ", stop)#proses membuang karakter selain huruf diganti spasi/sub=substitusi(mereplace semua pola RE)
stopword.append(stop)#proses memasukan/mengupdate kalimat2 kedalam stopword
#s.close()#proses menutup file
print("\nDaftar Stopword: \n", stopword)

#TOKENIZING DOKUMEN#
bagOfWords = dataSet#insialisasi bank kata(bag of word) yang isinya sama dengan variabel dataSet
for x in range(0, 266):#file dokumen yg akan di looping
    bagOfWords[x] = dataSet[x].split()#isi dari 'variabel dataSet' di pecah2 menjadi satuan kata lalu di copy ke sebuah variabel indeks ke-x
print("\nTokenizing: \n", bagOfWords)

#TOKENIZING STOPWORDS#
stopwords = stopword#insialisasi bank kata(variabel stopwords) yang isinya sama dengan variabel stopword
for x in range(0,1):#file dokumen yg akan di looping
    stopwords[x] = stopword[x].split()#isi dari 'variabel word' di pecah2 menjadi satuan kata lalu di copy ke sebuah variabel indeks ke-x
print("\nTokenizing Stopwords: \n", stopwords)

#FILTERING#
for x in range(0, 266):#looping pada 266 file dokumen abstrak
    for y in range(0, len(bagOfWords[x])):#looping pada setiap kata per dokumen
        for z in range(0, 780):#looping pada setiap kata stopwords
            if(bagOfWords[x][y] == stopwords[0][z]):#proses membandingkan setiap kata per dokumen dgn setiap kata pada stopword
                bagOfWords[x][y]=''#jika ditemukan kata yang tidak penting maka kata tsb dihapus
print("\nFiltering: \n", bagOfWords)

#KATA BERSIH/Mengembalikan kata2 yg sudah tidak ada kata yg 'tidak penting' menjadi kalimat utuh/dokumen#
for i in range(0, len(bagOfWords)):#looping untuk seluruh kata pada bank kata
    bagOfWords[i] = filter(bool, bagOfWords[i])#menghapus kata yg kosong
    dataSet[i] = ' '.join(bagOfWords[i])#menggabungkan kata demi kata dengan sebuah pemisah spasi per dokumen
print("\nKata Bersih: \n", dataSet)

#VSM & TFIDF#
VSM = CountVectorizer().fit_transform(dataSet) #method vector space model dari library scikit learn melakukan perubahan menjadi sebuah vektor
#tfidf = TfidfTransformer() #method tfidf dari library scikit learn di copy ke variabel tfidf
TFIDF = TfidfTransformer().fit_transform(VSM) #method tfidf dari library scikit learn melakukan perubahan menjadi sebuah nilai
#print (CountVectorizer().vocabulary)
print("\nVSM: \n", VSM)
#print("\n", VSM.todense())
print("\nTFIDF: \n", TFIDF)
#hhprint(TFIDF.todense())

#KONVERSI LABEL#
#Pendidikan = 0, RPL = 1, TKJ = 2, MM = 3#
label_manual =  [1,1,1,2,3,3,1,1,0,2,3,3,1,2, ## data 1 - 14
                 1,1,2,2,0,1,3,3,3,2,2,2,2,2, ## data 15 - 28
                 2,1,1,3,1,1,1,1,1,3,3,0,1,1, ## data 29 - 42
                 1,0,0,0,2,0,1,1,1,1,1,1,1,1, ## data 43 - 56
                 2,2,2,3,0,0,0,1,0,1,1,1,2,2, ## data 57 - 70
                 3,1,1,1,0,0,3,2,1,0,1,3,3,3, ## data 71 - 84
                 3,3,3,3,3,3,1,2,3,3,1,3,3,3, ## data 85 - 98
                 0,3,2,0,3,3,3,1,1,1,2,2,2,1, ## data 99 - 112
                 1,1,1,3,1,0,0,0,3,1,3,3,3,3, ## data 113 - 126
                 3,3,3,3,3,3,3,3,3,3,2,2,2,0, ## data 127 - 140
                 1,3,3,1,1,1,1,1,1,1,1,1,1,1, ## data 141 - 154
                 1,1,1,1,1,1,1,3,3,3,3,3,3,3, ## data 155 - 168
                 1,1,1,1,1,1,1,1,1,1,3,1,1,2, ## data 169 - 182
                 0,0,2,2,1,1,1,2,2,2,2,1,0,3, ## data 183 - 196
                 1,1,3,3,3,3,1,1,1,1,1,2,1,0, ## data 197 - 210
                 1,1,0,0,0,2,2,2,0,0,3,3,3,0, ## data 211 - 224
                 0,0,0,0,0,0,0,0,1,1,1,1,1,1, ## data 225 - 238
                 1,1,1,3,1,1,1,1,1,1,1,1,1,1, ## data 239 - 252
                 1,2,1,1,1,1,1,1,1,3,0,3,3,3] ## data 253 - 266

#METHOD MENGHITUNG RATA2 AKURASI#
akurasi = []
akurasi1 = []
akurasi2 = []
akurasi3 = []
def avg_akurasiLinear(): ## nama fungsi
    total = 0 ## pengosongan variabel
    for i in range(10): ## looping 10x karena ada 10 fold
        total = total + akurasi[i] ## tiap looping nilai total akan ditambahkan dengan nilai akurasi tiap fold
    print("-------------------------------------------------------------------------------------------------------") ## cetak pembatas
    print("Rata-rata akurasi keseluruhan SVM LinearSVC adalah :", total / 10) ## cetak rata-rata akurasi
def avg_akurasiSVM(): ## nama fungsi
    total = 0 ## pengosongan variabel
    for i in range(10): ## looping 10x karena ada 10 fold
        total = total + akurasi1[i] ## tiap looping nilai total akan ditambahkan dengan nilai akurasi tiap fold
    print("Rata-rata akurasi keseluruhan SVM kernel Linear adalah :", total / 10) ## cetak rata-rata akurasi
def avg_akurasiPolynomial(): ## nama fungsi
    total = 0 ## pengosongan variabel
    for i in range(10): ## looping 10x karena ada 10 fold
        total = total + akurasi2[i] ## tiap looping nilai total akan ditambahkan dengan nilai akurasi tiap fold
    print("Rata-rata akurasi keseluruhan SVM kernel Polynomial adalah :", total / 10) ## cetak rata-rata akurasi
def avg_akurasiRBF(): ## nama fungsi
    total = 0 ## pengosongan variabel
    for i in range(10): ## looping 10x karena ada 10 fold
        total = total + akurasi3[i] ## tiap looping nilai total akan ditambahkan dengan nilai akurasi tiap fold
    print("Rata-rata akurasi keseluruhan SVM kernel RBF adalah :", total / 10) ## cetak rata-rata akurasi

kFoldCrossValidation = KFold(n_splits=10)#fungsi K-Fold Cross Validation melakukan insialisasi 10x iterasi
for latih, uji in kFoldCrossValidation.split(TFIDF, label_manual):#proses looping yg masing2 pernah jadi data latih maupun uji
    print("-----------------------------------------------------------------------")
    print("Banyak Data Latih: ", len(latih))
    print("Banyak Data Uji: ", len(uji))
    print("\nData Latih: \n", latih)
    print("\nData Uji: \n", uji)

    dataLatih1, dataUji1 = TFIDF[latih], TFIDF[uji]#proses inisialisasi dari masing2 data latih/uji dijadikan nilai tfidf lalu di copy ke variabel dataLatih/Uji1
    label_manual = np.array([1, 1, 1, 2, 3, 3, 1, 1, 0, 2, 3, 3, 1, 2,  ## data 1 - 14
                             1, 1, 2, 2, 0, 1, 3, 3, 3, 2, 2, 2, 2, 2,  ## data 15 - 28
                             2, 1, 1, 3, 1, 1, 1, 1, 1, 3, 3, 0, 1, 1,  ## data 29 - 42
                             1, 0, 0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1,  ## data 43 - 56
                             2, 2, 2, 3, 0, 0, 0, 1, 0, 1, 1, 1, 2, 2,  ## data 57 - 70
                             3, 1, 1, 1, 0, 0, 3, 2, 1, 0, 1, 3, 3, 3,  ## data 71 - 84
                             3, 3, 3, 3, 3, 3, 1, 2, 3, 3, 1, 3, 3, 3,  ## data 85 - 98
                             0, 3, 2, 0, 3, 3, 3, 1, 1, 1, 2, 2, 2, 1,  ## data 99 - 112
                             1, 1, 1, 3, 1, 0, 0, 0, 3, 1, 3, 3, 3, 3,  ## data 113 - 126
                             3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 0,  ## data 127 - 140
                             1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  ## data 141 - 154
                             1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3,  ## data 155 - 168
                             1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 2,  ## data 169 - 182
                             0, 0, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1, 0, 3,  ## data 183 - 196
                             1, 1, 3, 3, 3, 3, 1, 1, 1, 1, 1, 2, 1, 0,  ## data 197 - 210
                             1, 1, 0, 0, 0, 2, 2, 2, 0, 0, 3, 3, 3, 0,  ## data 211 - 224
                             0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,  ## data 225 - 238
                             1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  ## data 239 - 252
                             1, 2, 1, 1, 1, 1, 1, 1, 1, 3, 0, 3, 3, 3])  ## data 253 - 266

    dataLatih2, dataUji2 = label_manual[latih], label_manual[uji]#proses inisialisasi dari masing2 data latih/uji dibentuk ke label untuk proses prediksi lalu di copy ke variabel dataLatih/Uji2

    SVMLinear = svm.LinearSVC().fit(dataLatih1, dataLatih2)#data latih melakukan proses pelatihan dengan algoritma SVM
    prediksi = SVMLinear.predict(dataUji1)#proses prediksi dari data latih yang sudah tersimpan sebagai model
    SVM = svm.SVC(kernel='linear').fit(dataLatih1, dataLatih2)  # data latih melakukan proses pelatihan dengan algoritma SVM
    prediksi1 = SVM.predict(dataUji1)  # proses prediksi dari data latih yang sudah tersimpan sebagai model
    SVMPoly = svm.SVC(kernel='poly', degree=3).fit(dataLatih1, dataLatih2)  # data latih melakukan proses pelatihan dengan algoritma SVM
    prediksi2 = SVMPoly.predict(dataUji1)  # proses prediksi dari data latih yang sudah tersimpan sebagai model
    SVMRBF = svm.SVC(kernel='rbf', gamma=0.7).fit(dataLatih1, dataLatih2)  # data latih melakukan proses pelatihan dengan algoritma SVM
    prediksi3 = SVMRBF.predict(dataUji1)  # proses prediksi dari data latih yang sudah tersimpan sebagai model

    print("\nHasil Prediksi SVM Linear: \n", prediksi)
    print("\nHasil Prediksi SVM: \n", prediksi1)
    print("\nHasil Prediksi SVM Polynomial: \n", prediksi2)
    print("\nHasil Prediksi SVM RBF: \n", prediksi3)

    print("\nConfusion Matrix: \n", metrics.confusion_matrix(dataUji2, prediksi1))#proses pembetukan metriks

    akurasi.append(accuracy_score(dataUji2, prediksi))
    akurasi1.append(accuracy_score(dataUji2, prediksi1))
    akurasi2.append(accuracy_score(dataUji2, prediksi2))
    akurasi3.append(accuracy_score(dataUji2, prediksi3))

    print("\nAkurasi SVM LinearSVC: ", accuracy_score(dataUji2, prediksi))
    print("\nAkurasi SVM kernel Linear: ", accuracy_score(dataUji2, prediksi1))
    print("\nAkurasi SVM kernel Polynomial: ", accuracy_score(dataUji2, prediksi2))
    print("\nAkurasi SVM kernel RBF: ", accuracy_score(dataUji2, prediksi3))
    print()\

    label = ['Pendidikan', 'RPL', 'TKJ', 'MM']
    print(metrics.classification_report(dataUji2, prediksi1, target_names=label))#proses pembentukan confusin matrix

avg_akurasiLinear()
avg_akurasiSVM()
avg_akurasiPolynomial()
avg_akurasiRBF()

Case Folding: 
 ['pengembangan aplikasi pembangkit paket soal tipe pilihan ganda berbasis web pada mata pelajaran sistem operasi', 'pengembangan aplikasi pembayaran siswa pada yayasan perguruan islam as sa adah pondok kelapa', 'pengembangan aplikasi penerimaan siswa baru pada yayasan perguruan islam as sa adah pondok kelapa jakarta timur', 'analisis cache dan kompresi proxy pada raspberry pi di jaringan hotspot smk negeri    jakarta', 'analisis dan desain kebutuhan elemen multimedia gambar ilustrasi pada sistem repositori multimedia pembelajaran perakitan komputer di sekolah menengah kejuruan', 'analisis dan desain kebutuhan elemen multimedia video pada sistem repositori multimedia pembelajaran perakitan komputer di sekolah menengah kejuruan', 'analisis dan perancangan kebutuhan sistem e learning berbasis moodle pada program studi pendidikan teknik informatika dan komputer universitas negeri jakarta', 'analisis dan perancangan sistem penerimaan mahasiswa baru universitas negeri jakarta


Filtering: 
 [['pengembangan', 'aplikasi', 'pembangkit', 'paket', '', 'tipe', 'pilihan', 'ganda', 'berbasis', 'web', '', '', 'pelajaran', 'sistem', 'operasi'], ['pengembangan', 'aplikasi', 'pembayaran', 'siswa', '', 'yayasan', 'perguruan', 'islam', 'as', 'sa', 'adah', 'pondok', 'kelapa'], ['pengembangan', 'aplikasi', 'penerimaan', 'siswa', '', '', 'yayasan', 'perguruan', 'islam', 'as', 'sa', 'adah', 'pondok', 'kelapa', 'jakarta', 'timur'], ['analisis', 'cache', '', 'kompresi', 'proxy', '', 'raspberry', 'pi', '', 'jaringan', 'hotspot', 'smk', 'negeri', 'jakarta'], ['analisis', '', 'desain', 'kebutuhan', 'elemen', 'multimedia', 'gambar', 'ilustrasi', '', 'sistem', 'repositori', 'multimedia', 'pembelajaran', 'perakitan', 'komputer', '', 'sekolah', 'menengah', 'kejuruan'], ['analisis', '', 'desain', 'kebutuhan', 'elemen', 'multimedia', 'video', '', 'sistem', 'repositori', 'multimedia', 'pembelajaran', 'perakitan', 'komputer', '', 'sekolah', 'menengah', 'kejuruan'], ['analisis', '', 'peran

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [2 2 1 2 3 1 1 1 1 1 3 3 1 1 1 1 0 0 0 2 1 1 1 1 1 1 1]

Hasil Prediksi SVM: 
 [2 2 1 2 3 1 1 1 1 1 3 3 1 1 1 1 0 0 0 2 1 1 1 1 1 1 1]

Hasil Prediksi SVM Polynomial: 
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

Hasil Prediksi SVM RBF: 
 [2 2 1 2 1 1 1 1 1 1 3 3 1 1 1 1 0 0 0 2 1 1 1 1 1 1 1]

Confusion Matrix: 
 [[ 3  2  0  0]
 [ 0 15  1  0]
 [ 0  0  3  0]
 [ 0  0  0  3]]

Akurasi SVM LinearSVC:  0.8888888888888888

Akurasi SVM kernel Linear:  0.8888888888888888

Akurasi SVM kernel Polynomial:  0.5925925925925926

Akurasi SVM kernel RBF:  0.8518518518518519

              precision    recall  f1-score   support

  Pendidikan       1.00      0.60      0.75         5
         RPL       0.88      0.94      0.91        16
         TKJ       0.75      1.00      0.86         3
          MM       1.00      1.00      1.00         3

    accuracy                           0.89        27
   macro avg       0.91      0.88      0.88        27
weighted a

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [3 3 3 3 3 3 3 3 3 1 1 3 3 1 3 3 3 0 1 1 0 3 3 1 1 1 1]

Hasil Prediksi SVM: 
 [3 3 3 3 3 3 3 3 3 1 1 3 3 1 3 3 3 0 1 1 0 3 1 1 1 1 1]

Hasil Prediksi SVM Polynomial: 
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

Hasil Prediksi SVM RBF: 
 [1 3 3 3 3 3 1 1 3 1 1 3 1 1 3 3 1 1 1 1 3 3 1 1 1 1 1]

Confusion Matrix: 
 [[ 2  0  0  0]
 [ 0  5  0  0]
 [ 0  2  0  0]
 [ 0  3  0 15]]

Akurasi SVM LinearSVC:  0.8518518518518519

Akurasi SVM kernel Linear:  0.8148148148148148

Akurasi SVM kernel Polynomial:  0.18518518518518517

Akurasi SVM kernel RBF:  0.5555555555555556

              precision    recall  f1-score   support

  Pendidikan       1.00      1.00      1.00         2
         RPL       0.50      1.00      0.67         5
         TKJ       0.00      0.00      0.00         2
          MM       1.00      0.83      0.91        18

    accuracy                           0.81        27
   macro avg       0.62      0.71      0.64        27
weighted 

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [3 2 2 2 1 1 3 1 1 1 1 1 1 0 1 1 1 1 3 1 3 3 1 1 1 1 3]

Hasil Prediksi SVM: 
 [3 2 2 2 1 1 3 1 1 1 1 1 1 0 1 1 1 1 3 1 3 3 1 1 1 1 3]

Hasil Prediksi SVM Polynomial: 
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

Hasil Prediksi SVM RBF: 
 [3 2 1 2 1 1 3 1 1 1 1 1 1 1 1 1 1 1 3 1 3 3 1 1 1 1 3]

Confusion Matrix: 
 [[ 0  1  0  0]
 [ 1 15  0  3]
 [ 0  0  3  0]
 [ 0  1  0  3]]

Akurasi SVM LinearSVC:  0.7777777777777778

Akurasi SVM kernel Linear:  0.7777777777777778

Akurasi SVM kernel Polynomial:  0.7037037037037037

Akurasi SVM kernel RBF:  0.7777777777777778

              precision    recall  f1-score   support

  Pendidikan       0.00      0.00      0.00         1
         RPL       0.88      0.79      0.83        19
         TKJ       1.00      1.00      1.00         3
          MM       0.50      0.75      0.60         4

    accuracy                           0.78        27
   macro avg       0.60      0.63      0.61        27
weighted a

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [1 2 2 2 2 1 0 1 1 1 1 3 3 3 1 1 1 1 1 1 1 0 1 1 0 0]

Hasil Prediksi SVM: 
 [1 2 2 2 2 1 0 1 1 1 1 3 3 3 1 1 1 1 1 1 1 0 1 1 0 0]

Hasil Prediksi SVM Polynomial: 
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

Hasil Prediksi SVM RBF: 
 [1 2 1 2 2 1 0 1 1 1 1 3 1 3 1 1 1 1 1 1 1 0 1 1 0 0]

Confusion Matrix: 
 [[ 4  0  0  0]
 [ 0 12  0  0]
 [ 0  1  4  0]
 [ 0  2  0  3]]

Akurasi SVM LinearSVC:  0.8846153846153846

Akurasi SVM kernel Linear:  0.8846153846153846

Akurasi SVM kernel Polynomial:  0.46153846153846156

Akurasi SVM kernel RBF:  0.8076923076923077

              precision    recall  f1-score   support

  Pendidikan       1.00      1.00      1.00         4
         RPL       0.80      1.00      0.89        12
         TKJ       1.00      0.80      0.89         5
          MM       1.00      0.60      0.75         5

    accuracy                           0.88        26
   macro avg       0.95      0.85      0.88        26
weighted avg     

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
