In [1]:
import json

# buka file JSON-nya dulu
with open('hasil_preprocessing.json','r') as myfile:
    
# load file JSON dari file yang sudah dibuka
    data = json.loads(myfile.read())
    
# cetak isi data 
# print (data)

In [2]:
hasil_preprocessing = []
for i in range(len(data['hasil_preprocessing'])):
    hasil_preprocessing.append(data['hasil_preprocessing'][i])

In [3]:
hasil_preprocessing

[['semua',
  'citra',
  'digital',
  'milik',
  'tampil',
  'visual',
  'muas',
  'mata',
  'manusia',
  'ketidakpuasan',
  'sebut',
  'timbul',
  'ada',
  'ganggu',
  'noise',
  'muncul',
  'bintikbintik',
  'sebab',
  'proses',
  'tangkap',
  'gambar',
  'sempurna',
  'cahaya',
  'rata',
  'akibat',
  'intensitas',
  'seragam',
  'kontras',
  'citra',
  'terlalu',
  'rendah',
  'objek',
  'sulit',
  'pisah',
  'latar',
  'belakang',
  'ganggu',
  'sebab',
  'kotorankotoran',
  'tempel',
  'citra',
  'perlu',
  'metode',
  'baik',
  'kualitas',
  'citra',
  'digital',
  'sebut',
  'denoise',
  'citra',
  'buah',
  'teknik',
  'guna',
  'baik',
  'gambar',
  'milik',
  'noise',
  'teknik',
  'guna',
  'ganti',
  'pixel',
  'noise',
  'pixel',
  'gambar',
  'dekat',
  'pixel',
  'noise',
  'sebut',
  'denoise',
  'guna',
  'bagai',
  'bahasa',
  'pemrograman',
  'guna',
  'metodemetode',
  'median',
  'filtering',
  'intensity',
  'filtering',
  'frequency',
  'filtering',
  'adaptive',

In [4]:
text_final=[' '.join(sen) for sen in hasil_preprocessing] 
# menghubungkan menjadi 1 kalimat 

In [5]:
text_final

['semua citra digital milik tampil visual muas mata manusia ketidakpuasan sebut timbul ada ganggu noise muncul bintikbintik sebab proses tangkap gambar sempurna cahaya rata akibat intensitas seragam kontras citra terlalu rendah objek sulit pisah latar belakang ganggu sebab kotorankotoran tempel citra perlu metode baik kualitas citra digital sebut denoise citra buah teknik guna baik gambar milik noise teknik guna ganti pixel noise pixel gambar dekat pixel noise sebut denoise guna bagai bahasa pemrograman guna metodemetode median filtering intensity filtering frequency filtering adaptive filtering new adaptive based median filter banyak metode guna teliti tulis pilih metode new adaptive based median filter',
 'suatu data informasi saji upa data teks upa audio video gambar zaman sekarang informasi sangat penting perlu informasi dapat citra citra image istilah gambar rupa salah satu komponen multimedia peran penting bentuk informasivisual banding data teks citra milik banyak informasi citr

In [6]:
print(len(text_final))

500


In [7]:
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
vectorizer = CountVectorizer(decode_error="replace")
transformer = TfidfTransformer()
TFIDF = transformer.fit_transform(vectorizer.fit_transform(text_final))

In [9]:
print(TFIDF)

  (0, 5238)	0.07185446395462078
  (0, 5047)	0.0576060453412996
  (0, 4962)	0.07852936685375327
  (0, 4901)	0.08746875004412077
  (0, 4860)	0.09847126565142006
  (0, 4850)	0.02710116569293715
  (0, 4834)	0.10200956215357417
  (0, 4795)	0.10178074805182717
  (0, 4782)	0.07116940535024534
  (0, 4703)	0.059272526660461934
  (0, 4406)	0.08919881075766832
  (0, 4386)	0.06189695045649361
  (0, 4384)	0.0956731381514687
  (0, 4312)	0.09829035504202345
  (0, 4304)	0.11717493611217299
  (0, 4085)	0.07116940535024534
  (0, 4013)	0.07852936685375327
  (0, 3894)	0.03173942885588886
  (0, 3727)	0.24927360257192963
  (0, 3725)	0.07330739106310237
  (0, 3716)	0.059272526660461934
  (0, 3672)	0.042921540684133765
  (0, 3604)	0.067526851246454
  (0, 3387)	0.06358671837094593
  (0, 3345)	0.3101917765558655
  :	:
  (499, 2798)	0.29405862000237015
  (499, 2763)	0.026655530046687085
  (499, 2666)	0.08671104311767566
  (499, 2654)	0.08388614555545688
  (499, 2546)	0.047314344446786324
  (499, 2511)	0.06709460

In [10]:
#Save model TFIDF
import pickle
pickle.dump(vectorizer.vocabulary_,open("TFIDF.pkl","wb"))

In [16]:
import csv
filedataolah = 'DataFix.csv'
f = open(filedataolah,'r')
reader = csv.reader(f, delimiter=';')
labels = []
for data in reader:
    labels.append(data[2])
kolom = labels.pop(0)
print(labels)

['Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik', 'Grafik',

In [23]:
label=[]
for i in range(len(labels)):
    if labels[i]=='Grafik':
        nilai = 0
        label.append(nilai)
    
    if labels[i]=='Artificial Intelligence dan Robotik':
        nilai = 1
        label.append(nilai)
    
    if labels[i]=='Database dan sistim retrieval informasi':
        nilai = 2
        label.append(nilai)
        
    if labels[i]=='Sistim Operasi dan Jaringan':
        nilai = 3
        label.append(nilai)
        
    if labels[i]=='Algoritma dan Struktur Data':
        nilai = 4
        label.append(nilai)

In [24]:
print(len(label))
print(len(text_final))
print(label)

500
500
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3

In [34]:
from sklearn import svm #method untuk pross perhitungan klasifikasi
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer #method untuk menghitung vsm dan tfidf
from sklearn import metrics #method untuk pembentukan matriks 1x1, 2x2, 3x3, ...
from sklearn.metrics import accuracy_score #method perhitungan akurasi
from sklearn.model_selection import KFold #Method perhitungan K-Fold
import numpy as np #scientific computing untuk array N-dimenesi
import re #re = regular expression
import itertools
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

In [35]:
print(label)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 

In [36]:
#METHOD MENGHITUNG RATA2 AKURASI#
akurasi = []
akurasi1 = []
akurasi2 = []
akurasi3 = []
def avg_akurasiLinear(): ## nama fungsi
    total = 0 ## pengosongan variabel
    for i in range(10): ## looping 10x karena ada 10 fold
        total = total + akurasi[i] ## tiap looping nilai total akan ditambahkan dengan nilai akurasi tiap fold
    print("-------------------------------------------------------------------------------------------------------") ## cetak pembatas
    print("Rata-rata akurasi keseluruhan SVM LinearSVC adalah :", total / 10) ## cetak rata-rata akurasi
def avg_akurasiSVM(): ## nama fungsi
    total = 0 ## pengosongan variabel
    for i in range(10): ## looping 10x karena ada 10 fold
        total = total + akurasi1[i] ## tiap looping nilai total akan ditambahkan dengan nilai akurasi tiap fold
    print("Rata-rata akurasi keseluruhan SVM kernel Linear adalah :", total / 10) ## cetak rata-rata akurasi
def avg_akurasiPolynomial(): ## nama fungsi
    total = 0 ## pengosongan variabel
    for i in range(10): ## looping 10x karena ada 10 fold
        total = total + akurasi2[i] ## tiap looping nilai total akan ditambahkan dengan nilai akurasi tiap fold
    print("Rata-rata akurasi keseluruhan SVM kernel Polynomial adalah :", total / 10) ## cetak rata-rata akurasi
def avg_akurasiRBF(): ## nama fungsi
    total = 0 ## pengosongan variabel
    for i in range(10): ## looping 10x karena ada 10 fold
        total = total + akurasi3[i] ## tiap looping nilai total akan ditambahkan dengan nilai akurasi tiap fold
    print("Rata-rata akurasi keseluruhan SVM kernel RBF adalah :", total / 10) ## cetak rata-rata akurasi


In [38]:
kFoldCrossValidation = KFold(n_splits=10, shuffle=True, random_state=42)#fungsi K-Fold Cross Validation melakukan insialisasi 10x iterasi
for latih, uji in kFoldCrossValidation.split(TFIDF, label):#proses looping yg masing2 pernah jadi data latih maupun uji
    print("-----------------------------------------------------------------------")
    print("Banyak Data Latih: ", len(latih))
    print("Banyak Data Uji: ", len(uji))
    print("\nData Latih: \n", latih)
    print("\nData Uji: \n", uji)
    
    dataLatih1, dataUji1 = TFIDF[latih], TFIDF[uji]#proses inisialisasi dari masing2 data latih/uji dijadikan nilai tfidf lalu di copy ke variabel dataLatih/Uji1
    label = np.array(label)
    dataLatih2, dataUji2 = label[latih], label[uji]#proses inisialisasi dari masing2 data latih/uji dibentuk ke label untuk proses prediksi lalu di copy ke variabel dataLatih/Uji2

    SVMLinear = svm.LinearSVC()
    modelLinear = SVMLinear.fit(dataLatih1, dataLatih2)#data latih melakukan proses pelatihan dengan algoritma SVM
    prediksi = modelLinear.predict(dataUji1)#proses prediksi dari data latih yang sudah tersimpan sebagai model
    SVM = svm.SVC(kernel='linear')
    modelSVM = SVM.fit(dataLatih1, dataLatih2)  # data latih melakukan proses pelatihan dengan algoritma SVM
    prediksi1 = modelSVM.predict(dataUji1)  # proses prediksi dari data latih yang sudah tersimpan sebagai model
    SVMPoly = svm.SVC(kernel='poly', degree=3)
    modelPoly = SVMPoly.fit(dataLatih1, dataLatih2)  # data latih melakukan proses pelatihan dengan algoritma SVM
    prediksi2 = modelPoly.predict(dataUji1)  # proses prediksi dari data latih yang sudah tersimpan sebagai model
    SVMRBF = svm.SVC(kernel='rbf', gamma=0.7)
    modelRBF = SVMRBF.fit(dataLatih1, dataLatih2)  # data latih melakukan proses pelatihan dengan algoritma SVM
    prediksi3 = modelRBF.predict(dataUji1)  # proses prediksi dari data latih yang sudah tersimpan sebagai model

    print("\nHasil Prediksi SVM Linear: \n", prediksi)
    print("\nHasil Prediksi SVM: \n", prediksi1)
    print("\nHasil Prediksi SVM Polynomial: \n", prediksi2)
    print("\nHasil Prediksi SVM RBF: \n", prediksi3)

    print("\nConfusion Matrix: \n", metrics.confusion_matrix(dataUji2, prediksi1))#proses pembetukan metriks

    akurasi.append(accuracy_score(dataUji2, prediksi))
    akurasi1.append(accuracy_score(dataUji2, prediksi1))
    akurasi2.append(accuracy_score(dataUji2, prediksi2))
    akurasi3.append(accuracy_score(dataUji2, prediksi3))

    print("\nAkurasi SVM LinearSVC: ", accuracy_score(dataUji2, prediksi))
    print("\nAkurasi SVM kernel Linear: ", accuracy_score(dataUji2, prediksi1))
    print("\nAkurasi SVM kernel Polynomial: ", accuracy_score(dataUji2, prediksi2))
    print("\nAkurasi SVM kernel RBF: ", accuracy_score(dataUji2, prediksi3))
    print()\

    label_target = ['grafik','artificial intelligance dan robotik','database dan sistim retrieval informasi','sistem operasi dan jaringan','algoritma dan struktur data']
    print(metrics.classification_report(dataUji2, prediksi1, target_names=label_target))#proses pembentukan confusin matrix

avg_akurasiLinear()
avg_akurasiSVM()
avg_akurasiPolynomial()
avg_akurasiRBF()

-----------------------------------------------------------------------
Banyak Data Latih:  450
Banyak Data Uji:  50

Data Latih: 
 [  1   3   4   5   6   7   8  10  12  13  14  15  16  17  18  19  20  21
  23  24  25  26  27  28  29  31  32  34  35  36  37  38  39  40  41  42
  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60
  61  62  64  65  66  67  69  71  72  74  75  78  79  80  81  82  83  85
  86  87  88  89  90  91  92  94  95  96  97  98  99 100 102 103 105 106
 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 174 175 176 177 178 179 180 181
 182 183 184 186 187 188 189 190 191 192 193 195 196 197 198 199 200 201
 202 203 204 205 206 207 208 210 212 213 214 215 216 217 218 219 220 221
 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 0 0 0 0 2 2 2 2 3 3 3 3 2 3 3 3 3 3 3
 1 4 4 4 1 4 1 4 2 4 2 4 2]

Hasil Prediksi SVM: 
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3
 1 4 4 3 4 4 1 4 2 4 2 4 2]

Hasil Prediksi SVM Polynomial: 
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]

Hasil Prediksi SVM RBF: 
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 2 2 2 2 3 3 3 3 2 3 3 3 3 3 3
 1 4 4 3 4 4 1 4 2 4 2 2 2]

Confusion Matrix: 
 [[ 0 15  0  0  0]
 [ 6  1  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  1 11  0]
 [ 0  2  3  1  7]]

Akurasi SVM LinearSVC:  0.42

Akurasi SVM kernel Linear:  0.44

Akurasi SVM kernel Polynomial:  0.06

Akurasi SVM kernel RBF:  0.42

                                         precision    recall  f1-score   support

                                 grafik       0.00      0.00      0.00        15
    artificial intelligance dan robotik       0.06      0.14     

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [1 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 0 0 0 2 2 2 3 2 2 2 3 3 3 3 3 3 3 3 3 3
 3 3 4 4 4 4 4 4 3 4 4 4 4]

Hasil Prediksi SVM: 
 [1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 0 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3
 3 3 4 4 4 4 4 4 3 4 4 4 4]

Hasil Prediksi SVM Polynomial: 
 [1 1 1 1 1 1 2 1 1 1 2 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]

Hasil Prediksi SVM RBF: 
 [1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 0 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 2
 3 3 4 4 4 4 4 4 3 4 4 4 4]

Confusion Matrix: 
 [[ 0 13  0  0  0]
 [ 5  2  0  0  0]
 [ 0  0  7  0  0]
 [ 0  0  0 12  0]
 [ 0  0  0  1 10]]

Akurasi SVM LinearSVC:  0.6

Akurasi SVM kernel Linear:  0.62

Akurasi SVM kernel Polynomial:  0.14

Akurasi SVM kernel RBF:  0.6

                                         precision    recall  f1-score   support

                                 grafik       0.00      0.00      0.00        13
    artificial intelligance dan robotik       0.13      0.29      0

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 0 0 2 2 4 2 2 2 2 3 2 2 2 2 2 2 2 2 0
 3 3 3 3 3 3 4 4 4 4 4 4 2]

Hasil Prediksi SVM: 
 [1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 0 0 2 2 4 2 2 2 2 3 2 2 2 2 2 2 2 2 0
 3 3 3 3 3 3 4 4 4 4 4 4 2]

Hasil Prediksi SVM Polynomial: 
 [4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4 4 4 4
 3 4 3 3 3 4 4 4 4 4 4 4 4]

Hasil Prediksi SVM RBF: 
 [1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 0 0 2 2 4 2 2 2 2 2 2 2 2 2 2 2 2 2 1
 3 3 3 3 3 3 4 4 4 4 4 4 2]

Confusion Matrix: 
 [[ 0 11  0  0  0]
 [ 8  1  0  0  0]
 [ 0  0 14  1  1]
 [ 1  0  0  6  0]
 [ 0  0  1  0  6]]

Akurasi SVM LinearSVC:  0.54

Akurasi SVM kernel Linear:  0.54

Akurasi SVM kernel Polynomial:  0.22

Akurasi SVM kernel RBF:  0.56

                                         precision    recall  f1-score   support

                                 grafik       0.00      0.00      0.00        11
    artificial intelligance dan robotik       0.08      0.11     

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [1 1 1 0 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 3 3 3 3 3 3
 3 3 4 4 4 4 4 4 4 4 4 4 4]

Hasil Prediksi SVM: 
 [1 1 1 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 3 3 3 3 3 3
 3 3 4 4 4 4 4 4 4 4 4 4 4]

Hasil Prediksi SVM Polynomial: 
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]

Hasil Prediksi SVM RBF: 
 [1 1 1 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 3 3 3 3 3 3
 3 3 4 4 4 4 4 4 4 4 4 4 4]

Confusion Matrix: 
 [[ 3  8  0  0  0]
 [15  0  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0  8  0]
 [ 0  0  0  0 11]]

Akurasi SVM LinearSVC:  0.52

Akurasi SVM kernel Linear:  0.54

Akurasi SVM kernel Polynomial:  0.1

Akurasi SVM kernel RBF:  0.54

                                         precision    recall  f1-score   support

                                 grafik       0.17      0.27      0.21        11
    artificial intelligance dan robotik       0.00      0.00      

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 4 4 0 0 0 0 0 2 2 2 2 2 2 2 2 3 2 3 3 3 3 3
 3 3 2 3 3 3 3 3 4 4 4 4 3]

Hasil Prediksi SVM: 
 [1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 4 4 0 0 0 0 0 2 2 2 2 2 2 2 2 3 2 3 3 3 3 3
 3 3 2 3 3 3 3 3 4 4 4 4 3]

Hasil Prediksi SVM Polynomial: 
 [4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4]

Hasil Prediksi SVM RBF: 
 [1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 4 4 0 0 0 0 0 2 2 2 2 2 2 2 2 3 2 3 3 3 3 3
 3 3 2 3 3 3 3 3 4 4 4 4 3]

Confusion Matrix: 
 [[ 0  9  0  0  0]
 [11  0  0  0  2]
 [ 0  0  9  1  0]
 [ 0  0  1 12  0]
 [ 0  0  0  1  4]]

Akurasi SVM LinearSVC:  0.5

Akurasi SVM kernel Linear:  0.5

Akurasi SVM kernel Polynomial:  0.1

Akurasi SVM kernel RBF:  0.5

                                         precision    recall  f1-score   support

                                 grafik       0.00      0.00      0.00         9
    artificial intelligance dan robotik       0.00      0.00      0.0

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [1 1 0 0 0 0 0 0 0 0 0 0 0 3 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 4 3 3 3 3 3 3 3
 3 2 4 4 4 4 4 4 4 2 3 4 4]

Hasil Prediksi SVM: 
 [1 0 0 0 0 0 0 0 0 0 0 0 0 3 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 4 3 3 3 3 3 3 3
 3 2 4 4 4 4 4 4 4 0 3 4 4]

Hasil Prediksi SVM Polynomial: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]

Hasil Prediksi SVM RBF: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 3 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 4 3 3 3 3 3 3 3
 3 2 4 4 4 4 4 4 4 2 3 4 4]

Confusion Matrix: 
 [[ 1  1  0  0  0]
 [11  0  0  0  0]
 [ 0  0 12  1  0]
 [ 0  0  0 11  1]
 [ 1  0  1  1  9]]

Akurasi SVM LinearSVC:  0.64

Akurasi SVM kernel Linear:  0.66

Akurasi SVM kernel Polynomial:  0.04

Akurasi SVM kernel RBF:  0.68

                                         precision    recall  f1-score   support

                                 grafik       0.08      0.50      0.13         2
    artificial intelligance dan robotik       0.00      0.00     

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [1 1 1 1 1 1 4 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3
 3 3 3 3 0 4 4 4 4 4 4 4 3]

Hasil Prediksi SVM: 
 [1 1 1 1 1 1 4 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3
 3 3 3 3 0 4 4 4 4 4 4 4 3]

Hasil Prediksi SVM Polynomial: 
 [4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4]

Hasil Prediksi SVM RBF: 
 [0 1 1 1 1 1 4 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3
 3 3 3 3 0 4 4 4 4 4 4 4 3]

Confusion Matrix: 
 [[ 0  8  0  0  1]
 [13  0  0  0  0]
 [ 0  0 11  0  0]
 [ 1  0  0  8  0]
 [ 0  0  0  1  7]]

Akurasi SVM LinearSVC:  0.52

Akurasi SVM kernel Linear:  0.52

Akurasi SVM kernel Polynomial:  0.16

Akurasi SVM kernel RBF:  0.54

                                         precision    recall  f1-score   support

                                 grafik       0.00      0.00      0.00         9
    artificial intelligance dan robotik       0.00      0.00     

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 0 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 3 3 3 2
 3 4 4 4 4 4 4 4 4 4 4 3 4]

Hasil Prediksi SVM: 
 [1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 0 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 3 3 3 2
 3 4 4 4 4 4 4 4 4 4 4 3 4]

Hasil Prediksi SVM Polynomial: 
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3]

Hasil Prediksi SVM RBF: 
 [1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 3 3 3 2
 3 4 4 4 4 4 4 4 4 4 3 3 4]

Confusion Matrix: 
 [[ 0 11  0  0  0]
 [ 6  1  0  0  0]
 [ 0  0 14  1  0]
 [ 0  0  1  4  0]
 [ 0  0  0  1 11]]

Akurasi SVM LinearSVC:  0.6

Akurasi SVM kernel Linear:  0.6

Akurasi SVM kernel Polynomial:  0.1

Akurasi SVM kernel RBF:  0.6

                                         precision    recall  f1-score   support

                                 grafik       0.00      0.00      0.00        11
    artificial intelligance dan robotik       0.08      0.14      0.1

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [1 1 0 1 1 1 1 1 1 1 0 0 0 0 0 3 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3
 3 3 4 3 4 4 4 4 4 4 4 4 4]

Hasil Prediksi SVM: 
 [1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 4 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3
 3 3 4 3 4 4 4 4 4 4 4 4 4]

Hasil Prediksi SVM Polynomial: 
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]

Hasil Prediksi SVM RBF: 
 [1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3
 3 3 4 3 4 4 4 4 4 4 4 4 4]

Confusion Matrix: 
 [[ 0 10  0  0  0]
 [ 4  1  0  0  0]
 [ 0  0 11  0  1]
 [ 0  0  0 12  0]
 [ 0  0  0  1 10]]

Akurasi SVM LinearSVC:  0.68

Akurasi SVM kernel Linear:  0.68

Akurasi SVM kernel Polynomial:  0.1

Akurasi SVM kernel RBF:  0.72

                                         precision    recall  f1-score   support

                                 grafik       0.00      0.00      0.00        10
    artificial intelligance dan robotik       0.09      0.20      

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 3 3 3 3 3 3 4
 3 3 3 4 4 4 4 4 3 3 0 4 4]

Hasil Prediksi SVM: 
 [1 0 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 3 3 3 3 3 3 4
 3 3 3 4 4 4 4 4 3 3 0 4 3]

Hasil Prediksi SVM Polynomial: 
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]

Hasil Prediksi SVM RBF: 
 [1 0 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 3 3 3 3 3 3 4
 3 3 3 4 4 4 4 4 3 3 0 4 3]

Confusion Matrix: 
 [[ 4  5  0  0  0]
 [13  0  0  0  0]
 [ 0  0  8  0  0]
 [ 0  0  0  9  1]
 [ 1  0  0  3  6]]

Akurasi SVM LinearSVC:  0.52

Akurasi SVM kernel Linear:  0.54

Akurasi SVM kernel Polynomial:  0.16

Akurasi SVM kernel RBF:  0.54

                                         precision    recall  f1-score   support

                                 grafik       0.22      0.44      0.30         9
    artificial intelligance dan robotik       0.00      0.00     

In [119]:
# save the model to disk
import pickle
filename = 'SVMLinier_model.sav'
pickle.dump(SVMLinear, open(filename, 'wb'))

In [120]:
# save the model to disk
import pickle
filename = 'SVM_model.sav'
pickle.dump(SVM, open(filename, 'wb'))

In [121]:
# save the model to disk
import pickle
filename = 'SVMPolynomial_model.sav'
pickle.dump(SVMPoly, open(filename, 'wb'))

In [122]:
# save the model to disk
import pickle
filename = 'SVMRBF_model.sav'
pickle.dump(SVMRBF, open(filename, 'wb'))

In [9]:
# save the model to disk
import pickle
filename = 'TFIDF.pickle'
pickle.dump(TFIDF, open(filename, 'wb'))