In [1]:
import json

# buka file JSON-nya dulu
with open('hasil_preprocessingDataBaru.json','r') as myfile:
    
# load file JSON dari file yang sudah dibuka
    data = json.loads(myfile.read())
    
# cetak isi data 
# print (data)

In [4]:
hasil_preprocessing = []
for i in range(len(data['hasil_preprocessing'])):
    hasil_preprocessing.append(data['hasil_preprocessing'][i])

In [5]:
hasil_preprocessing

[['analisis',
  'pola',
  'beli',
  'konsumen',
  'transaksi',
  'jual',
  'guna',
  'algoritma',
  'apriori'],
 ['terap',
  'data',
  'mining',
  'analisis',
  'pola',
  'beli',
  'produk',
  'guna',
  'algoritma',
  'apriori',
  'data',
  'transaksi',
  'jual',
  'studi',
  'kasus',
  'koperasi',
  'guru',
  'banjar',
  'kgb'],
 ['aplikasi',
  'deteksi',
  'wajah',
  'foto',
  'dijital',
  'sistem',
  'kenal',
  'wajah'],
 ['analisis',
  'banding',
  'kompleksitas',
  'algoritma',
  'urut',
  'nilai',
  'sorting'],
 ['analisis', 'ancang', 'teknologi', 'robot', 'sepak', 'bola'],
 ['algoritma',
  'bayesian',
  'network',
  'simulasi',
  'prediksi',
  'menang',
  'pilkada',
  'guna',
  'msbnx'],
 ['algoritma',
  'fpgrowth',
  'teknik',
  'market',
  'basket',
  'analysis',
  'sparepart',
  'komputer',
  'jasa',
  'servis',
  'komputer',
  'studi',
  'kasus',
  'cv',
  'karya',
  'computer',
  'center'],
 ['aplikasi',
  'cari',
  'bahan',
  'pustaka',
  'pustaka',
  'guna',
  'metode',
 

In [6]:
text_final=[' '.join(sen) for sen in hasil_preprocessing] 
# menghubungkan menjadi 1 kalimat 

In [7]:
text_final

['analisis pola beli konsumen transaksi jual guna algoritma apriori',
 'terap data mining analisis pola beli produk guna algoritma apriori data transaksi jual studi kasus koperasi guru banjar kgb',
 'aplikasi deteksi wajah foto dijital sistem kenal wajah',
 'analisis banding kompleksitas algoritma urut nilai sorting',
 'analisis ancang teknologi robot sepak bola',
 'algoritma bayesian network simulasi prediksi menang pilkada guna msbnx',
 'algoritma fpgrowth teknik market basket analysis sparepart komputer jasa servis komputer studi kasus cv karya computer center',
 'aplikasi cari bahan pustaka pustaka guna metode vector space model',
 'algoritma kohonen ubah citra graylevel jadi citra biner',
 'algoritma routing lingkung jaring grid guna teori graf',
 'analisa data mining guna market basket analysis tahu pola beli konsumen',
 'analisa desain paralelisasi needlemen',
 'analisa butuh waktu proses selesai traveling salesman problem',
 'analisa klasifikasi jenis pohon mangga dasar tekstur

In [8]:
print(len(text_final))

500


In [9]:
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
vectorizer = CountVectorizer(decode_error="replace")
transformer = TfidfTransformer()
TFIDF = transformer.fit_transform(vectorizer.fit_transform(text_final))

In [10]:
print (TFIDF)

  (0, 1560)	0.39563587147722645
  (0, 1155)	0.34710950232797194
  (0, 739)	0.41795065524956115
  (0, 662)	0.35484689584902107
  (0, 529)	0.16315559747047406
  (0, 173)	0.39563587147722645
  (0, 85)	0.37281930052799744
  (0, 67)	0.25244578245488464
  (0, 50)	0.1910957486861586
  (1, 1560)	0.23383558153923412
  (1, 1521)	0.17860909825260346
  (1, 1453)	0.18263279005283659
  (1, 1193)	0.26495425629778974
  (1, 1155)	0.20515468436063578
  (1, 924)	0.2121804209688128
  (1, 745)	0.3279297881167499
  (1, 706)	0.3279297881167499
  (1, 685)	0.17609510884568336
  (1, 662)	0.20972777301115914
  (1, 530)	0.2930857566260978
  (1, 529)	0.09643105382087573
  (1, 321)	0.3028136336599745
  (1, 173)	0.23383558153923412
  (1, 145)	0.3279297881167499
  (1, 85)	0.22035013565000497
  :	:
  (497, 1572)	0.4714204809762937
  (497, 1476)	0.4714204809762937
  (497, 1249)	0.4421193757478921
  (497, 555)	0.4714204809762937
  (497, 322)	0.3712393405022344
  (498, 1628)	0.35517569662842896
  (498, 1589)	0.4863268935

In [18]:
#Save model TFIDF
import pickle
pickle.dump(vectorizer.vocabulary_,open("TFIDFmodel_DataBaru.pkl","wb"))

In [11]:
import csv
filedataolah = 'DataBaru.csv'
f = open(filedataolah,'r')
reader = csv.reader(f, delimiter=';')
labels = []
for data in reader:
    labels.append(data[1])
kolom = labels.pop(0)
print(labels)

['Artificial Intelligance dan Robotik', 'Artificial Intelligance dan Robotik', 'Grafik', 'Database dan Sistim Retrieval Informasi', 'Artificial Intelligance dan Robotik', 'Artificial Intelligance dan Robotik', 'Artificial Intelligance dan Robotik', 'Database dan Sistim Retrieval Informasi', 'Grafik', 'Algoritma dan Struktur Data', 'Artificial Intelligance dan Robotik', 'Algoritma dan Struktur Data', 'Database dan Sistim Retrieval Informasi', 'Grafik', 'Grafik', 'Grafik', 'Database dan Sistim Retrieval Informasi', 'Database dan Sistim Retrieval Informasi', 'Algoritma dan Struktur Data', 'Algoritma dan Struktur Data', 'Artificial Intelligance dan Robotik', 'Artificial Intelligance dan Robotik', 'Sistim Operasi dan Jaringan', 'Artificial Intelligance dan Robotik', 'Artificial Intelligance dan Robotik', 'Database dan Sistim Retrieval Informasi', 'Artificial Intelligance dan Robotik', 'Grafik', 'Database dan Sistim Retrieval Informasi', 'Database dan Sistim Retrieval Informasi', 'Database d

In [12]:
label=[]
for i in range(len(labels)):
    if labels[i]=='Grafik':
        nilai = 0
        label.append(nilai)
    
    if labels[i]=='Artificial Intelligance dan Robotik':
        nilai = 1
        label.append(nilai)
    
    if labels[i]=='Database dan Sistim Retrieval Informasi':
        nilai = 2
        label.append(nilai)
        
    if labels[i]=='Sistim Operasi dan Jaringan':
        nilai = 3
        label.append(nilai)
        
    if labels[i]=='Algoritma dan Struktur Data':
        nilai = 4
        label.append(nilai)

In [13]:
print(len(label))
print(len(text_final))
print(label)

500
500
[1, 1, 0, 2, 1, 1, 1, 2, 0, 4, 1, 4, 2, 0, 0, 0, 2, 2, 4, 4, 1, 1, 3, 1, 1, 2, 1, 0, 2, 2, 2, 0, 0, 4, 0, 4, 3, 3, 3, 0, 4, 3, 3, 3, 4, 4, 3, 3, 3, 4, 3, 3, 4, 4, 2, 2, 3, 3, 3, 3, 3, 2, 1, 4, 4, 3, 3, 1, 3, 0, 2, 4, 3, 3, 2, 2, 0, 4, 3, 1, 1, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 0, 1, 2, 1, 4, 4, 1, 1, 1, 4, 2, 2, 4, 1, 1, 2, 2, 2, 1, 1, 0, 3, 1, 3, 4, 4, 2, 3, 1, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0, 0, 0, 0, 4, 3, 2, 1, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 4, 2, 4, 0, 4, 1, 3, 2, 2, 2, 4, 1, 4, 4, 4, 2, 4, 2, 2, 0, 0, 2, 2, 1, 1, 0, 1, 1, 2, 3, 3, 0, 4, 1, 4, 4, 4, 4, 4, 4, 4, 0, 2, 4, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 4, 3, 2, 2, 2, 4, 1, 3, 4, 4, 2, 2, 3, 4, 4, 1, 3, 4, 3, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 4, 4, 2, 0, 1, 1, 2, 2, 0, 2, 1, 4, 4, 4, 3, 3, 1, 3, 3, 4, 1, 1, 2, 3, 0, 1, 3, 3, 2, 4, 4, 3, 3, 3, 3, 1, 0, 2, 3, 3, 2, 2, 2, 2, 4, 0, 1, 1, 1, 4, 2, 3, 2, 3, 4, 4, 4, 2, 4, 2, 1, 0, 1, 1, 0, 4, 1, 1, 0, 4, 4, 2, 1, 3, 1, 1, 1, 4, 1, 1, 4, 4, 1

In [14]:
from sklearn import svm #method untuk pross perhitungan klasifikasi
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer #method untuk menghitung vsm dan tfidf
from sklearn import metrics #method untuk pembentukan matriks 1x1, 2x2, 3x3, ...
from sklearn.metrics import accuracy_score #method perhitungan akurasi
from sklearn.model_selection import KFold #Method perhitungan K-Fold
import numpy as np #scientific computing untuk array N-dimenesi
import  
import itertools
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

In [15]:
print(len(label))

500


In [16]:
#METHOD MENGHITUNG RATA2 AKURASI#
akurasi = []
akurasi1 = []
akurasi2 = []
akurasi3 = []
def avg_akurasiLinear(): ## nama fungsi
    total = 0 ## pengosongan variabel
    for i in range(10): ## looping 10x karena ada 10 fold
        total = total + akurasi[i] ## tiap looping nilai total akan ditambahkan dengan nilai akurasi tiap fold
    print("-------------------------------------------------------------------------------------------------------") ## cetak pembatas
    print("Rata-rata akurasi keseluruhan SVM LinearSVC adalah :", total / 10) ## cetak rata-rata akurasi
def avg_akurasiSVM(): ## nama fungsi
    total = 0 ## pengosongan variabel
    for i in range(10): ## looping 10x karena ada 10 fold
        total = total + akurasi1[i] ## tiap looping nilai total akan ditambahkan dengan nilai akurasi tiap fold
    print("Rata-rata akurasi keseluruhan SVM kernel Linear adalah :", total / 10) ## cetak rata-rata akurasi
def avg_akurasiPolynomial(): ## nama fungsi
    total = 0 ## pengosongan variabel
    for i in range(10): ## looping 10x karena ada 10 fold
        total = total + akurasi2[i] ## tiap looping nilai total akan ditambahkan dengan nilai akurasi tiap fold
    print("Rata-rata akurasi keseluruhan SVM kernel Polynomial adalah :", total / 10) ## cetak rata-rata akurasi
def avg_akurasiRBF(): ## nama fungsi
    total = 0 ## pengosongan variabel
    for i in range(10): ## looping 10x karena ada 10 fold
        total = total + akurasi3[i] ## tiap looping nilai total akan ditambahkan dengan nilai akurasi tiap fold
    print("Rata-rata akurasi keseluruhan SVM kernel RBF adalah :", total / 10) ## cetak rata-rata akurasi

In [17]:
kFoldCrossValidation = KFold(n_splits=10)#fungsi K-Fold Cross Validation melakukan insialisasi 10x iterasi
for latih, uji in kFoldCrossValidation.split(TFIDF, label):#proses looping yg masing2 pernah jadi data latih maupun uji
    print("-----------------------------------------------------------------------")
    print("Banyak Data Latih: ", len(latih))
    print("Banyak Data Uji: ", len(uji))
    print("\nData Latih: \n", latih)
    print("\nData Uji: \n", uji)
    
    dataLatih1, dataUji1 = TFIDF[latih], TFIDF[uji]#proses inisialisasi dari masing2 data latih/uji dijadikan nilai tfidf lalu di copy ke variabel dataLatih/Uji1
    label = np.array(label)
    dataLatih2, dataUji2 = label[latih], label[uji]#proses inisialisasi dari masing2 data latih/uji dibentuk ke label untuk proses prediksi lalu di copy ke variabel dataLatih/Uji2

    SVMLinear = svm.LinearSVC()
    modelLinear = SVMLinear.fit(dataLatih1, dataLatih2)#data latih melakukan proses pelatihan dengan algoritma SVM
    prediksi = modelLinear.predict(dataUji1)#proses prediksi dari data latih yang sudah tersimpan sebagai model
    SVM = svm.SVC(kernel='linear')
    modelSVM = SVM.fit(dataLatih1, dataLatih2)  # data latih melakukan proses pelatihan dengan algoritma SVM
    prediksi1 = modelSVM.predict(dataUji1)  # proses prediksi dari data latih yang sudah tersimpan sebagai model
    SVMPoly = svm.SVC(kernel='poly', degree=3)
    modelPoly = SVMPoly.fit(dataLatih1, dataLatih2)  # data latih melakukan proses pelatihan dengan algoritma SVM
    prediksi2 = modelPoly.predict(dataUji1)  # proses prediksi dari data latih yang sudah tersimpan sebagai model
    SVMRBF = svm.SVC(kernel='rbf', gamma=0.7)
    modelRBF = SVMRBF.fit(dataLatih1, dataLatih2)  # data latih melakukan proses pelatihan dengan algoritma SVM
    prediksi3 = modelRBF.predict(dataUji1)  # proses prediksi dari data latih yang sudah tersimpan sebagai model

    print("\nHasil Prediksi SVM Linear: \n", prediksi)
    print("\nHasil Prediksi SVM: \n", prediksi1)
    print("\nHasil Prediksi SVM Polynomial: \n", prediksi2)
    print("\nHasil Prediksi SVM RBF: \n", prediksi3)

    print("\nConfusion Matrix: \n", metrics.confusion_matrix(dataUji2, prediksi1))#proses pembetukan metriks

    akurasi.append(accuracy_score(dataUji2, prediksi))
    akurasi1.append(accuracy_score(dataUji2, prediksi1))
    akurasi2.append(accuracy_score(dataUji2, prediksi2))
    akurasi3.append(accuracy_score(dataUji2, prediksi3))

    print("\nAkurasi SVM LinearSVC: ", accuracy_score(dataUji2, prediksi))
    print("\nAkurasi SVM kernel Linear: ", accuracy_score(dataUji2, prediksi1))
    print("\nAkurasi SVM kernel Polynomial: ", accuracy_score(dataUji2, prediksi2))
    print("\nAkurasi SVM kernel RBF: ", accuracy_score(dataUji2, prediksi3))
    print()\

    label_target = ['grafik','artificial intelligance dan robotik','database dan sistim retrieval informasi','sistem operasi dan jaringan','algoritma dan struktur data']
    print(metrics.classification_report(dataUji2, prediksi1, target_names=label_target))#proses pembentukan confusin matrix

avg_akurasiLinear()
avg_akurasiSVM()
avg_akurasiPolynomial()
avg_akurasiRBF()

-----------------------------------------------------------------------
Banyak Data Latih:  450
Banyak Data Uji:  50

Data Latih: 
 [ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103
 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121
 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139
 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175
 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193
 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211
 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229
 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247
 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [1 1 0 2 3 1 1 1 0 4 1 3 1 0 3 0 2 2 4 4 1 1 3 1 1 2 1 0 2 3 2 0 0 4 0 4 3
 3 3 0 4 3 3 3 4 1 3 3 3 4]

Hasil Prediksi SVM: 
 [1 1 0 2 3 1 1 1 0 4 1 4 1 0 3 0 1 2 4 4 1 1 3 1 1 2 1 0 2 3 2 0 0 4 0 4 3
 3 3 0 4 3 3 3 4 1 3 3 3 4]

Hasil Prediksi SVM Polynomial: 
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]

Hasil Prediksi SVM RBF: 
 [1 1 0 2 3 1 1 1 0 4 1 3 1 0 3 0 1 2 4 4 1 1 3 1 1 2 1 0 2 3 2 0 0 4 0 4 3
 3 3 0 4 3 3 3 4 1 3 3 3 4]

Confusion Matrix: 
 [[ 9  0  0  1  0]
 [ 0 10  0  1  0]
 [ 0  3  5  1  0]
 [ 0  0  0 10  0]
 [ 0  1  0  0  9]]

Akurasi SVM LinearSVC:  0.86

Akurasi SVM kernel Linear:  0.86

Akurasi SVM kernel Polynomial:  0.18

Akurasi SVM kernel RBF:  0.84

                                         precision    recall  f1-score   support

                                 grafik       1.00      0.90      0.95        10
    artificial intelligance dan robotik       0.71      0.91     

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [3 3 4 4 2 2 3 3 3 3 3 1 1 4 4 3 3 0 3 0 4 4 3 3 1 4 0 4 1 1 1 2 2 2 2 2 2
 2 4 4 4 4 4 4 0 1 2 1 4 4]

Hasil Prediksi SVM: 
 [3 3 4 4 2 2 3 3 3 3 3 1 1 4 4 3 3 1 3 0 4 4 3 3 1 4 0 4 1 1 1 2 2 2 2 2 2
 2 4 4 4 4 4 4 0 1 2 1 4 4]

Hasil Prediksi SVM Polynomial: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]

Hasil Prediksi SVM RBF: 
 [3 3 4 4 2 1 3 3 3 3 3 1 1 4 4 3 3 1 3 0 4 4 3 3 1 4 0 4 1 1 1 2 2 2 2 2 2
 2 4 4 4 4 4 4 0 1 2 1 4 4]

Confusion Matrix: 
 [[ 3  0  0  0  0]
 [ 0  6  0  0  0]
 [ 0  2 10  0  2]
 [ 0  1  0 12  0]
 [ 0  0  0  0 14]]

Akurasi SVM LinearSVC:  0.88

Akurasi SVM kernel Linear:  0.9

Akurasi SVM kernel Polynomial:  0.06

Akurasi SVM kernel RBF:  0.88

                                         precision    recall  f1-score   support

                                 grafik       1.00      1.00      1.00         3
    artificial intelligance dan robotik       0.67      1.00      

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [1 1 1 4 4 2 3 1 1 2 2 2 1 0 0 3 1 3 4 4 2 3 1 0 0 0 0 0 0 0 3 3 3 0 0 0 0
 0 4 3 4 1 4 4 0 0 0 0 0 0]

Hasil Prediksi SVM: 
 [1 1 1 4 4 2 3 1 1 2 2 2 1 0 0 3 1 3 4 4 2 3 1 0 0 0 0 0 0 0 3 3 3 0 0 0 0
 0 4 3 4 1 4 4 0 0 0 0 0 0]

Hasil Prediksi SVM Polynomial: 
 [3 3 3 3 4 3 4 3 3 3 2 3 3 3 3 3 3 3 4 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 4 3 3 3 3 3 3 3]

Hasil Prediksi SVM RBF: 
 [1 1 1 4 4 2 3 1 1 2 2 2 1 0 0 3 1 3 4 4 2 3 1 0 0 0 0 0 0 0 3 3 3 0 0 0 0
 0 4 3 4 1 4 4 0 0 0 0 0 0]

Confusion Matrix: 
 [[19  0  0  0  0]
 [ 1  9  0  0  0]
 [ 0  0  5  0  2]
 [ 0  0  0  7  0]
 [ 0  0  0  1  6]]

Akurasi SVM LinearSVC:  0.92

Akurasi SVM kernel Linear:  0.92

Akurasi SVM kernel Polynomial:  0.22

Akurasi SVM kernel RBF:  0.92

                                         precision    recall  f1-score   support

                                 grafik       0.95      1.00      0.97        19
    artificial intelligance dan robotik       1.00      0.90     

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [0 0 0 0 0 0 0 0 3 0 0 1 1 4 2 4 1 4 1 3 2 1 2 4 1 4 3 4 2 4 2 2 0 0 2 2 1
 1 0 1 1 2 3 3 0 4 2 4 4 4]

Hasil Prediksi SVM: 
 [0 0 0 0 0 0 0 0 3 0 0 1 1 4 2 4 1 4 1 3 2 1 2 4 1 4 3 4 2 4 2 2 0 0 2 2 1
 1 0 1 1 2 3 3 0 4 2 4 4 4]

Hasil Prediksi SVM Polynomial: 
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3]

Hasil Prediksi SVM RBF: 
 [0 0 0 0 0 0 0 0 3 0 0 1 1 4 2 4 1 4 1 3 2 1 2 4 1 4 3 4 2 4 2 2 0 0 2 2 1
 1 0 1 1 2 3 3 0 4 2 4 4 4]

Confusion Matrix: 
 [[14  1  0  1  0]
 [ 0  8  1  0  0]
 [ 0  1  9  0  0]
 [ 0  0  0  3  0]
 [ 0  0  0  1 11]]

Akurasi SVM LinearSVC:  0.9

Akurasi SVM kernel Linear:  0.9

Akurasi SVM kernel Polynomial:  0.06

Akurasi SVM kernel RBF:  0.9

                                         precision    recall  f1-score   support

                                 grafik       1.00      0.88      0.93        16
    artificial intelligance dan robotik       0.80      0.89      0.

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [4 4 4 4 0 2 4 0 0 0 0 1 2 2 2 3 1 4 3 2 2 2 4 1 3 4 4 2 2 3 4 4 1 3 4 3 0
 0 0 0 0 0 4 0 0 1 0 0 4 4]

Hasil Prediksi SVM: 
 [4 4 4 4 0 2 4 0 0 0 0 1 2 2 2 3 1 4 3 2 2 2 4 1 3 4 4 2 2 3 4 4 1 3 4 3 0
 0 0 0 0 0 4 0 0 1 0 0 4 4]

Hasil Prediksi SVM Polynomial: 
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]

Hasil Prediksi SVM RBF: 
 [4 4 4 4 0 2 4 0 0 0 0 1 2 2 2 3 1 4 3 2 2 2 4 1 3 4 4 2 2 3 4 4 1 3 4 3 0
 0 0 0 0 0 1 0 0 1 0 0 4 4]

Confusion Matrix: 
 [[15  0  0  0  0]
 [ 0  3  0  0  1]
 [ 0  2  9  1  0]
 [ 0  0  0  5  0]
 [ 0  0  0  0 14]]

Akurasi SVM LinearSVC:  0.92

Akurasi SVM kernel Linear:  0.92

Akurasi SVM kernel Polynomial:  0.08

Akurasi SVM kernel RBF:  0.94

                                         precision    recall  f1-score   support

                                 grafik       1.00      1.00      1.00        15
    artificial intelligance dan robotik       0.60      0.75     

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [2 4 1 1 2 2 0 2 4 4 4 4 3 3 1 3 3 3 3 2 2 2 0 1 3 4 2 4 4 3 3 3 3 3 0 2 3
 3 2 2 2 2 4 0 1 1 1 4 2 3]

Hasil Prediksi SVM: 
 [2 4 1 1 2 2 0 2 4 4 4 4 3 3 1 3 3 3 3 2 2 2 0 1 3 4 2 4 4 3 3 3 3 2 0 2 3
 3 2 2 2 2 4 0 1 1 1 4 2 3]

Hasil Prediksi SVM Polynomial: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]

Hasil Prediksi SVM RBF: 
 [2 4 1 1 2 2 0 2 4 4 4 4 2 3 1 2 3 3 3 1 2 2 0 1 3 4 2 4 4 3 3 3 3 1 0 2 3
 3 2 2 2 2 4 0 1 1 1 4 2 3]

Confusion Matrix: 
 [[ 4  0  0  0  1]
 [ 0  7  2  1  1]
 [ 0  0 12  0  0]
 [ 0  0  1 12  1]
 [ 0  0  0  1  7]]

Akurasi SVM LinearSVC:  0.84

Akurasi SVM kernel Linear:  0.84

Akurasi SVM kernel Polynomial:  0.1

Akurasi SVM kernel RBF:  0.84

                                         precision    recall  f1-score   support

                                 grafik       1.00      0.80      0.89         5
    artificial intelligance dan robotik       1.00      0.64      

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [2 3 4 4 4 2 2 2 1 0 1 1 0 4 1 1 0 4 4 2 1 3 1 1 1 2 1 1 4 4 1 1 0 1 1 2 0
 1 1 1 2 3 2 2 3 4 3 4 0 2]

Hasil Prediksi SVM: 
 [2 3 4 4 4 2 2 2 1 1 1 1 0 4 1 1 0 4 4 2 1 3 1 1 1 2 1 1 4 4 1 1 1 1 1 2 0
 1 1 1 2 3 2 2 3 4 3 4 0 2]

Hasil Prediksi SVM Polynomial: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]

Hasil Prediksi SVM RBF: 
 [2 3 4 4 4 2 2 2 2 1 1 1 0 4 1 1 0 4 4 2 1 3 1 1 1 2 1 1 4 1 1 1 1 1 1 2 0
 2 1 1 2 3 2 2 3 2 3 4 0 2]

Confusion Matrix: 
 [[ 3  1  0  0  0]
 [ 1 19  1  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0  5  0]
 [ 0  0  4  0 10]]

Akurasi SVM LinearSVC:  0.86

Akurasi SVM kernel Linear:  0.86

Akurasi SVM kernel Polynomial:  0.08

Akurasi SVM kernel RBF:  0.78

                                         precision    recall  f1-score   support

                                 grafik       0.75      0.75      0.75         4
    artificial intelligance dan robotik       0.95      0.90     

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [0 1 2 1 2 4 3 3 1 2 1 1 3 2 0 0 0 0 0 0 1 4 1 2 3 3 4 0 0 0 3 3 2 0 4 2 2
 4 4 4 1 1 4 4 0 4 3 4 4 3]

Hasil Prediksi SVM: 
 [0 1 2 1 2 4 3 3 1 3 1 1 3 2 0 0 0 0 0 0 1 4 1 2 3 3 4 0 0 0 4 3 2 0 4 2 2
 4 4 4 1 1 4 4 0 4 3 4 4 3]

Hasil Prediksi SVM Polynomial: 
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]

Hasil Prediksi SVM RBF: 
 [0 1 2 1 2 4 3 3 1 2 1 1 3 2 0 0 0 0 0 0 1 4 1 2 3 3 4 0 0 0 3 3 2 0 4 2 2
 4 4 4 1 1 4 4 0 4 3 4 4 3]

Confusion Matrix: 
 [[12  0  0  0  0]
 [ 0  7  0  0  0]
 [ 0  2  5  0  1]
 [ 0  0  1  9  1]
 [ 0  0  1  0 11]]

Akurasi SVM LinearSVC:  0.88

Akurasi SVM kernel Linear:  0.88

Akurasi SVM kernel Polynomial:  0.14

Akurasi SVM kernel RBF:  0.88

                                         precision    recall  f1-score   support

                                 grafik       1.00      1.00      1.00        12
    artificial intelligance dan robotik       0.78      1.00     

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



Hasil Prediksi SVM Linear: 
 [0 4 3 2 3 3 0 1 3 3 3 0 0 2 4 3 3 4 1 1 2 2 4 0 2 2 2 2 0 0 0 2 0 3 3 3 3
 2 3 3 1 2 1 1 1 1 1 0 3 3]

Hasil Prediksi SVM: 
 [0 4 3 2 3 3 0 1 3 3 3 0 0 2 4 3 3 4 1 1 2 2 4 0 2 2 2 2 0 0 0 2 0 3 3 3 3
 2 3 3 1 2 1 1 1 1 1 0 3 3]

Hasil Prediksi SVM Polynomial: 
 [4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4]

Hasil Prediksi SVM RBF: 
 [4 4 3 2 3 3 0 1 3 3 3 0 0 2 4 3 3 4 1 1 2 2 4 0 1 2 2 2 0 0 0 2 0 3 3 3 3
 2 3 3 1 2 1 1 1 1 1 0 3 3]

Confusion Matrix: 
 [[ 9  0  0  0  0]
 [ 0  9  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 16  0]
 [ 1  0  1  0  4]]

Akurasi SVM LinearSVC:  0.96

Akurasi SVM kernel Linear:  0.96

Akurasi SVM kernel Polynomial:  0.12

Akurasi SVM kernel RBF:  0.92

                                         precision    recall  f1-score   support

                                 grafik       0.90      1.00      0.95         9
    artificial intelligance dan robotik       1.00      1.00     

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [19]:
# save the model to disk
import pickle
filename = 'SVMLinier_modelDataBaru.sav'
pickle.dump(SVMLinear, open(filename, 'wb'))

In [20]:
# save the model to disk
import pickle
filename = 'SVM_modelDataBaru.sav'
pickle.dump(SVM, open(filename, 'wb'))

In [21]:
# save the model to disk
import pickle
filename = 'SVMPolynomial_modelDataaru.sav'
pickle.dump(SVMPoly, open(filename, 'wb'))

In [22]:
# save the model to disk
import pickle
filename = 'SVMRBF_modelDataBaru.sav'
pickle.dump(SVMRBF, open(filename, 'wb'))